export const projects = [
  // มิติที่ 1: อุตสาหกรรมสีเขียว
  {
    id: 1,
    name: 'ส่งเสริมปูนซีเมนต์ไฮดรอลิก มอก. 2594 ในทุกงานก่อสร้างจังหวัด',
    dimension_id: 1,
    dimension_name: 'Green Industry & Urban Planning',
    description: 'รณรงค์และออกข้อบัญญัติท้องถิ่นให้งานก่อสร้างในจังหวัดใช้ปูนซีเมนต์ไฮดรอลิกลดโลกร้อน',
    indicator: 'สัดส่วนการทดแทนปูนปอร์ตแลนด์ปกติด้วยไฮดรอลิก',
    unit: '%',
    target_value: 100,
    current_value: 82.5,
    budget_baht: 4500000,
    agency: 'อุตสาหกรรมจังหวัดสระบุรี',
    status: 'In Progress'
  },
  {
    id: 2,
    name: 'โครงการทดสอบและวิจัยปูนซีเมนต์ดินเผาหินปูน (LC3)',
    dimension_id: 1,
    dimension_name: 'Green Industry & Urban Planning',
    description: 'วิจัยการผลิตดินเผาหินปูนร่วมกับสมาคมอุตสาหกรรมปูนซีเมนต์ไทย (TCMA) เพื่อลดอัตราส่วนคลิงเกอร์',
    indicator: 'ปริมาณการปล่อยคาร์บอนต่อตันปูนซีเมนต์ที่ลดลง',
    unit: '%',
    target_value: 40,
    current_value: 15,
    budget_baht: 12000000,
    agency: 'อุตสาหกรรมจังหวัดสระบุรี',
    status: 'In Progress'
  },
  {
    id: 3,
    name: 'ศูนย์เรียนรู้เทคโนโลยีดักจับและกักเก็บคาร์บอน (CCUS Showcase)',
    dimension_id: 1,
    dimension_name: 'Green Industry & Urban Planning',
    description: 'จัดตั้งศูนย์สาธิตการดักจับก๊าซคาร์บอนไดออกไซด์จากเตาเผาปูนซีเมนต์ในพื้นที่สระบุรี',
    indicator: 'จำนวนโรงงานปูนซีเมนต์ที่เข้าร่วมศึกษา CCUS',
    unit: 'แห่ง',
    target_value: 3,
    current_value: 1,
    budget_baht: 35000000,
    agency: 'สนง.ทรัพยากรธรรมชาติและสิ่งแวดล้อมจังหวัด (ทสจ.)',
    status: 'Planning'
  },
  // มิติที่ 2: พลังงานสะอาด
  {
    id: 4,
    name: 'โซลาร์ลอยน้ำคลองเพรียว (Khlong Priaw Floating Solar)',
    dimension_id: 2,
    dimension_name: 'Clean Energy Transition',
    description: 'ติดตั้งแผงโซลาร์ลอยน้ำบนอ่างเก็บน้ำ/คลองสาธารณะคลองเพรียวเพื่อจ่ายไฟให้ชุมชนและสำนักงาน',
    indicator: 'กำลังการผลิตไฟฟ้าติดตั้ง',
    unit: 'kW',
    target_value: 5000,
    current_value: 2500,
    budget_baht: 85000000,
    agency: 'สำนักงานพลังงานจังหวัดสระบุรี',
    status: 'In Progress'
  },
  {
    id: 5,
    name: 'ระบบโครงข่ายไฟฟ้าอัจฉริยะ Smart/Micro Grid ชุมชนเมืองแก่งคอย',
    dimension_id: 2,
    dimension_name: 'Clean Energy Transition',
    description: 'ทดลองติดตั้งระบบไมโครกริดเชื่อมโยงโซลาร์รูฟท็อปและระบบกักเก็บพลังงานแบตเตอรี่ในโรงพยาบาลและชุมชนแก่งคอย',
    indicator: 'เสถียรภาพการจ่ายไฟและการลดการซื้อไฟจากการไฟฟ้า',
    unit: '%',
    target_value: 30,
    current_value: 10,
    budget_baht: 42000000,
    agency: 'สำนักงานพลังงานจังหวัดสระบุรี',
    status: 'Planning'
  },
  {
    id: 6,
    name: 'โครงการพลังงานแสงอาทิตย์บนหลังคาสำหรับวิสาหกิจชุมชนและ SME',
    dimension_id: 2,
    dimension_name: 'Clean Energy Transition',
    description: 'สนับสนุนเงินทุนดอกเบี้ยต่ำและการติดตั้ง Solar Rooftop ให้กับผู้ประกอบการ SME ในพื้นที่',
    indicator: 'จำนวน SME ที่ติดตั้งและใช้งานโซลาร์เซลล์',
    unit: 'ราย',
    target_value: 150,
    current_value: 45,
    budget_baht: 18000000,
    agency: 'อุตสาหกรรมจังหวัดสระบุรี',
    status: 'In Progress'
  },
  // มิติที่ 3: จัดการของเสีย
  {
    id: 7,
    name: 'โครงการแปรรูปขยะเป็นพลังงานความร้อน (RDF Cluster)',
    dimension_id: 3,
    dimension_name: 'Waste Management',
    description: 'ผลิตเชื้อเพลิงขยะมูลฝอย (Refuse Derived Fuel) ป้อนเข้าสู่โรงงานปูนซีเมนต์ทดแทนถ่านหิน',
    indicator: 'ปริมาณขยะชุมชนที่นำไปแปรรูปเป็น RDF',
    unit: 'ตัน/วัน',
    target_value: 500,
    current_value: 320,
    budget_baht: 25000000,
    agency: 'องค์การบริหารส่วนจังหวัดสระบุรี',
    status: 'In Progress'
  },
  {
    id: 8,
    name: 'ระบบก๊าซชีวภาพชุมชนจากฟาร์มปศุสัตว์และเศษอาหาร (Biogas Cluster)',
    dimension_id: 3,
    dimension_name: 'Waste Management',
    description: 'รวบรวมน้ำเสียและเศษอาหารจากฟาร์มสุกรและตลาดในจังหวัดเพื่อหมักก๊าซชีวภาพสำหรับชุมชนและโรงงานไฟฟ้า',
    indicator: 'กำลังการผลิตก๊าซชีวภาพเทียบเท่าไฟฟ้า',
    unit: 'kW',
    target_value: 1200,
    current_value: 600,
    budget_baht: 15000000,
    agency: 'สำนักงานพลังงานจังหวัดสระบุรี',
    status: 'In Progress'
  },
  {
    id: 9,
    name: 'โครงการธนาคารขยะชุมชนและโรงเรียนคาร์บอนต่ำ (Zero Waste Schools)',
    dimension_id: 3,
    dimension_name: 'Waste Management',
    description: 'สร้างพฤติกรรมการคัดแยกขยะตั้งแต่ต้นทางผ่านโรงเรียนและศูนย์เรียนรู้ชุมชน 13 อำเภอ',
    indicator: 'จำนวนชุมชนที่เข้าร่วมโครงการแยกขยะและเปิดธนาคารขยะ',
    unit: 'ชุมชน',
    target_value: 100,
    current_value: 65,
    budget_baht: 3000000,
    agency: 'ทสจ.สระบุรี',
    status: 'In Progress'
  },
  // มิติที่ 4: เกษตรคาร์บอนต่ำ
  {
    id: 10,
    name: 'โครงการทำนาเปียกสลับแห้ง (Alternate Wet and Dry: AWD)',
    dimension_id: 4,
    dimension_name: 'Low-Carbon Agriculture',
    description: 'ส่งเสริมให้เกษตรกรทำนาข้าวแบบเปียกสลับแห้งเพื่อลดก๊าซมีเทนและประหยัดน้ำ ครอบคลุมพื้นที่เป้าหมาย 50,000 ไร่',
    indicator: 'พื้นที่ทำนาเปียกสลับแห้งสะสม',
    unit: 'ไร่',
    target_value: 50000,
    current_value: 18500,
    budget_baht: 8000000,
    agency: 'เกษตรจังหวัดสระบุรี',
    status: 'In Progress'
  },
  {
    id: 11,
    name: 'โครงการส่งเสริมปลูกหญ้าเนเปียร์เป็นพืชพลังงานร่วมชุมชน',
    dimension_id: 4,
    dimension_name: 'Low-Carbon Agriculture',
    description: 'สนับสนุนเกษตรกรปลูกหญ้าโตเร็วเพื่อส่งจำหน่ายให้กับโรงไฟฟ้าชีวมวลและโรงงานปูนซีเมนต์',
    indicator: 'พื้นที่ปลูกหญ้าเนเปียร์พืชพลังงาน',
    unit: 'ไร่',
    target_value: 12000,
    current_value: 4800,
    budget_baht: 5000000,
    agency: 'เกษตรจังหวัดสระบุรี',
    status: 'In Progress'
  },
  // มิติที่ 5: เพิ่มพื้นที่สีเขียว
  {
    id: 12,
    name: 'โครงการฟื้นฟูเหมืองหินและป่าชุมชนเฉลิมพระเกียรติ',
    dimension_id: 5,
    dimension_name: 'Green Areas & Community Forests',
    description: 'ฟื้นฟูสภาพเหมืองหินปูนที่หมดอายุประทานบัตรให้กลายเป็นแหล่งท่องเที่ยวเชิงนิเวศและพื้นที่ป่าชุมชน',
    indicator: 'พื้นที่ป่าชุมชนและเหมืองหินที่ได้รับการฟื้นฟู',
    unit: 'ไร่',
    target_value: 15000,
    current_value: 6200,
    budget_baht: 18000000,
    agency: 'ทสจ.สระบุรี',
    status: 'In Progress'
  },
  {
    id: 13,
    name: 'เครือข่ายป่าชุมชนคาร์บอนเครดิตสระบุรี (45 ป่าชุมชน)',
    dimension_id: 5,
    dimension_name: 'Green Areas & Community Forests',
    description: 'ขึ้นทะเบียนป่าชุมชน 45 แห่งเข้าร่วมโครงการ T-VER ขององค์การบริหารจัดการก๊าซเรือนกระจก (TGO)',
    indicator: 'จำนวนป่าชุมชนที่ได้รับการขึ้นทะเบียนคาร์บอนเครดิต',
    unit: 'แห่ง',
    target_value: 45,
    current_value: 22,
    budget_baht: 6000000,
    agency: 'ทสจ.สระบุรี',
    status: 'In Progress'
  },
  {
    id: 14,
    name: 'ป่าไม้ในเมืองและทางเดินสีเขียว (Urban Pocket Parks)',
    dimension_id: 5,
    dimension_name: 'Green Areas & Community Forests',
    description: 'เพิ่มพื้นที่สีเขียวขนาดเล็กในเขตเทศบาลเมืองสระบุรี แก่งคอย และเฉลิมพระเกียรติ',
    indicator: 'พื้นที่สวนสาธารณะและทางเดินสีเขียวในเมือง',
    unit: 'ตารางเมตร',
    target_value: 50000,
    current_value: 20000,
    budget_baht: 12000000,
    agency: 'ท้องถิ่นจังหวัดสระบุรี',
    status: 'In Progress'
  },
  // มิติที่ 6: ขนส่งและโลจิสติกส์
  {
    id: 15,
    name: 'ส่งเสริมยานยนต์ไฟฟ้า (EV) ในกลุ่มรถบรรทุกขนส่งอุตสาหกรรม',
    dimension_id: 6,
    dimension_name: 'Transport & Logistics',
    description: 'ร่วมมือกับสมาคมขนส่งสระบุรีเปลี่ยนผ่านหัวลากปูนซีเมนต์เป็น EV Truck',
    indicator: 'สัดส่วนรถบรรทุกขนส่งปูนที่เป็น EV',
    unit: '%',
    target_value: 20,
    current_value: 3.5,
    budget_baht: 45000000,
    agency: 'ขนส่งจังหวัดสระบุรี',
    status: 'In Progress'
  },
  {
    id: 16,
    name: 'โครงข่ายสถานีอัดประจุไฟฟ้าความเร็วสูงสำหรับรถบรรทุกหนัก (Heavy-Duty EV Charging Stations)',
    dimension_id: 6,
    dimension_name: 'Transport & Logistics',
    description: 'จัดตั้งสถานีชาร์จกำลังสูง (DC Ultra Fast Charge) ตามเส้นทางขนส่งสายหลัก',
    indicator: 'จำนวนจุดบริการชาร์จสำหรับรถบรรทุกขนาดใหญ่',
    unit: 'แห่ง',
    target_value: 8,
    current_value: 2,
    budget_baht: 24000000,
    agency: 'สำนักงานพลังงานจังหวัดสระบุรี',
    status: 'In Progress'
  },
  {
    id: 17,
    name: 'ระบบบริการขนส่งสาธารณะไฟฟ้าในเมือง (EV Smart Shuttle)',
    dimension_id: 6,
    dimension_name: 'Transport & Logistics',
    description: 'นำร่องรถมินิบัสไฟฟ้าให้บริการฟรีรอบตัวเมืองสระบุรีเพื่อลดมลพิษ PM2.5 และคาร์บอน',
    indicator: 'จำนวนผู้โดยสารใช้บริการต่อวัน',
    unit: 'คน/วัน',
    target_value: 1500,
    current_value: 650,
    budget_baht: 9500000,
    agency: 'ท้องถิ่นจังหวัดสระบุรี',
    status: 'In Progress'
  }
];

export const initialSummaryData = {
  gpp_gdp_saraburi_thb: '245,000,000,000',
  cement_production_pct_national: 80,
  national_ghg_emissions_rank: 3,
  reduction_target_tons_co2e: 5000000,
  current_reduced_tons_co2e: 3250000,
  target_year: 2027,
  total_projects: 17,
  active_projects: 15,
  pilot_areas_target: 38,
  pilot_areas_current: 26,
  core_dimensions_target: 6,
  core_dimensions_current: 6,
  forest_target_rai: 15000,
  forest_current_rai: 10500,
  agri_target_rai: 50000,
  agri_current_rai: 28500,
  total_budget_baht: 367000000,
  partnership_model: '4Ps (Public-Private-People Partnership)',
  wef_initiative_member: true
};

export const initialCmsArticles = [
  {
    id: 1,
    title: 'สระบุรีแซนด์บ็อกซ์ เปิดตัวความร่วมมือระดับโลกในเวที WEF Transitioning Industrial Clusters',
    slug: 'saraburi-wef-announcement',
    category: 'News',
    summary: 'สมาคมอุตสาหกรรมปูนซีเมนต์ไทยร่วมกับภาครัฐและจังหวัดสระบุรีประกาศความก้าวหน้าการเป็นเมืองคาร์บอนต่ำแห่งแรกของไทยบนเวทีโลก',
    content: `<p>สระบุรีแซนด์บ็อกซ์ได้เข้าร่วมเครือข่ายความร่วมมือ <strong>Transitioning Industrial Clusters</strong> ของ World Economic Forum (WEF) เพื่อแลกเปลี่ยนเทคโนโลยีและดึงดูดการลงทุนสีเขียวจากต่างประเทศ โดยตั้งเป้าหมายลดการปล่อยก๊าซเรือนกระจก 5 ล้านตัน CO2e ภายในปี 2027 ด้วยโมเดลความร่วมมือ 4Ps (Public-Private-People Partnership)</p><h3>จุดเด่นของความร่วมมือระดับโลก</h3><p>โครงการนี้มุ่งเน้นการยกระดับอุตสาหกรรมปูนซีเมนต์และพลังงานสะอาดในพื้นที่จังหวัดสระบุรีให้เป็นต้นแบบสากล โดยประสานความร่วมมือระหว่างภาครัฐ เอกชน และสถาบันการศึกษาระดับโลก</p><blockquote>"สระบุรีแซนด์บ็อกซ์เป็นหนึ่งในตัวอย่างความสำเร็จของการร่วมมือ Area-based ที่ชัดเจนและนำไปสู่การปฏิบัติจริงในภูมิภาคอาเซียน"</blockquote><p>นอกจากนี้ ยังมีการผลักดันนวัตกรรมการใช้พลังงานแสงอาทิตย์ การนำขยะชุมชนมาแปรรูปเป็นพลังงานทดแทน (RDF) และการเพิ่มพื้นที่ป่าชุมชนเพื่อกักเก็บคาร์บอนอย่างยั่งยืน</p>`,
    image_url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80',
    gallery_images: [
      'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=1200&q=80'
    ],
    author: 'แอดมินประชาสัมพันธ์',
    is_published: true,
    published_at: '2026-07-01T08:00:00.000Z',
    created_at: '2026-07-01T08:00:00.000Z',
    updated_at: '2026-07-01T08:00:00.000Z'
  },
  {
    id: 2,
    title: 'ก้าวสำคัญ "สระบุรีแซนด์บ็อกซ์กินได้" ผลักดันระบบคาร์บอนมาร์เก็ตท้องถิ่นเพื่อสร้างรายได้ให้ชุมชน',
    slug: 'saraburi-edible-carbon-market',
    category: 'Announcement',
    summary: 'แผนขับเคลื่อนปี 2569 เน้นเศรษฐกิจฐานรากจากการขายคาร์บอนเครดิตภาคเกษตรและป่าชุมชนให้ชาวบ้านสัมผัสได้จริง',
    content: `<p>กระทรวงทรัพยากรธรรมชาติฯ ร่วมกับ TGO และจังหวัดสระบุรี นำร่องโครงการ <strong>"สระบุรีแซนด์บ็อกซ์กินได้"</strong> พัฒนากลไกการซื้อขายคาร์บอนเครดิตผ่านโครงการนาเปียกสลับแห้ง (AWD) และระบบป่าชุมชน 45 แห่งในพื้นที่ เพื่อนำผลตอบแทนกลับคืนเป็นรายได้และสิทธิประโยชน์โดยตรงกับชุมชนในพื้นที่</p><h3>ประโยชน์ที่ชุมชนได้รับโดยตรง</h3><ul><li>รายได้เสริมจากการขายคาร์บอนเครดิตภาคการเกษตรและการฟื้นฟูป่า</li><li>การลดต้นทุนค่าน้ำมันและน้ำในการทำนาข้าวด้วยวิธี AWD</li><li>การสร้างแหล่งท่องเที่ยวเชิงอนุรักษ์และตลาดสินค้าคาร์บอนต่ำในชุมชน</li></ul><p>โดยมีเป้าหมายขยายผลให้ครอบคลุมพื้นที่เกษตรกรรม 50,000 ไร่ และป่าชุมชน 15,000 ไร่ ทั่วจังหวัดสระบุรี</p>`,
    image_url: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=1200&q=80',
    gallery_images: [
      'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80'
    ],
    author: 'แอดมินประชาสัมพันธ์',
    is_published: true,
    published_at: '2026-07-15T10:30:00.000Z',
    created_at: '2026-07-15T10:30:00.000Z',
    updated_at: '2026-07-15T10:30:00.000Z'
  }
];
