export const projects = [
  // มิติที่ 1: อุตสาหกรรมสีเขียว
  {
    id: 1,
    name: 'ส่งเสริมปูนซีเมนต์ไฮดรอลิก มอก. 2594 ในทุกงานก่อสร้างจังหวัด',
    dimension_id: 1,
    dimension_name: 'Green Industry & Urban Planning',
    description: 'รณรงค์และออกข้อบัญญัติท้องถิ่นให้งานก่อสร้างในจังหวัดใช้ปูนซีเมนต์ไฮดรอลิกลดโลกร้อน',
    indicator: 'สัดส่วนการทดแทนปูนปอร์ตแลนด์ปกติด้วยไฮดรอลิก',
    unit: '%',
    target_value: 100,
    current_value: 82.5,
    budget_baht: 4500000,
    agency: 'อุตสาหกรรมจังหวัดสระบุรี',
    status: 'In Progress'
  },
  {
    id: 2,
    name: 'โครงการทดสอบและวิจัยปูนซีเมนต์ดินเผาหินปูน (LC3)',
    dimension_id: 1,
    dimension_name: 'Green Industry & Urban Planning',
    description: 'วิจัยการผลิตดินเผาหินปูนร่วมกับสมาคมอุตสาหกรรมปูนซีเมนต์ไทย (TCMA) เพื่อลดอัตราส่วนคลิงเกอร์',
    indicator: 'ปริมาณการปล่อยคาร์บอนต่อตันปูนซีเมนต์ที่ลดลง',
    unit: '%',
    target_value: 40,
    current_value: 15,
    budget_baht: 12000000,
    agency: 'อุตสาหกรรมจังหวัดสระบุรี',
    status: 'In Progress'
  },
  {
    id: 3,
    name: 'ศูนย์เรียนรู้เทคโนโลยีดักจับและกักเก็บคาร์บอน (CCUS Showcase)',
    dimension_id: 1,
    dimension_name: 'Green Industry & Urban Planning',
    description: 'จัดตั้งศูนย์สาธิตการดักจับก๊าซคาร์บอนไดออกไซด์จากเตาเผาปูนซีเมนต์ในพื้นที่สระบุรี',
    indicator: 'จำนวนโรงงานปูนซีเมนต์ที่เข้าร่วมศึกษา CCUS',
    unit: 'แห่ง',
    target_value: 3,
    current_value: 1,
    budget_baht: 35000000,
    agency: 'สนง.ทรัพยากรธรรมชาติและสิ่งแวดล้อมจังหวัด (ทสจ.)',
    status: 'Planning'
  },
  // มิติที่ 2: พลังงานสะอาด
  {
    id: 4,
    name: 'โซลาร์ลอยน้ำคลองเพรียว (Khlong Priaw Floating Solar)',
    dimension_id: 2,
    dimension_name: 'Clean Energy Transition',
    description: 'ติดตั้งแผงโซลาร์ลอยน้ำบนอ่างเก็บน้ำ/คลองสาธารณะคลองเพรียวเพื่อจ่ายไฟให้ชุมชนและสำนักงาน',
    indicator: 'กำลังการผลิตไฟฟ้าติดตั้ง',
    unit: 'kW',
    target_value: 5000,
    current_value: 2500,
    budget_baht: 85000000,
    agency: 'สำนักงานพลังงานจังหวัดสระบุรี',
    status: 'In Progress'
  },
  {
    id: 5,
    name: 'ระบบโครงข่ายไฟฟ้าอัจฉริยะ Smart/Micro Grid ชุมชนเมืองแก่งคอย',
    dimension_id: 2,
    dimension_name: 'Clean Energy Transition',
    description: 'ทดลองติดตั้งระบบไมโครกริดเชื่อมโยงโซลาร์รูฟท็อปและระบบกักเก็บพลังงานแบตเตอรี่ในโรงพยาบาลและชุมชนแก่งคอย',
    indicator: 'เสถียรภาพการจ่ายไฟและการลดการซื้อไฟจากการไฟฟ้า',
    unit: '%',
    target_value: 30,
    current_value: 10,
    budget_baht: 42000000,
    agency: 'สำนักงานพลังงานจังหวัดสระบุรี',
    status: 'Planning'
  },
  {
    id: 6,
    name: 'โครงการพลังงานแสงอาทิตย์บนหลังคาสำหรับวิสาหกิจชุมชนและ SME',
    dimension_id: 2,
    dimension_name: 'Clean Energy Transition',
    description: 'สนับสนุนเงินทุนดอกเบี้ยต่ำและการติดตั้ง Solar Rooftop ให้กับผู้ประกอบการ SME ในพื้นที่',
    indicator: 'จำนวน SME ที่ติดตั้งและใช้งานโซลาร์เซลล์',
    unit: 'ราย',
    target_value: 150,
    current_value: 45,
    budget_baht: 18000000,
    agency: 'อุตสาหกรรมจังหวัดสระบุรี',
    status: 'In Progress'
  },
  // มิติที่ 3: จัดการของเสีย
  {
    id: 7,
    name: 'โครงการแปรรูปขยะเป็นพลังงานความร้อน (RDF Cluster)',
    dimension_id: 3,
    dimension_name: 'Waste Management',
    description: 'ผลิตเชื้อเพลิงขยะมูลฝอย (Refuse Derived Fuel) ป้อนเข้าสู่โรงงานปูนซีเมนต์ทดแทนถ่านหิน',
    indicator: 'ปริมาณขยะชุมชนที่นำไปแปรรูปเป็น RDF',
    unit: 'ตัน/วัน',
    target_value: 500,
    current_value: 320,
    budget_baht: 25000000,
    agency: 'องค์การบริหารส่วนจังหวัดสระบุรี',
    status: 'In Progress'
  },
  {
    id: 8,
    name: 'ระบบก๊าซชีวภาพชุมชนจากฟาร์มปศุสัตว์และเศษอาหาร (Biogas Cluster)',
    dimension_id: 3,
    dimension_name: 'Waste Management',
    description: 'รวบรวมน้ำเสียและเศษอาหารจากฟาร์มสุกรและตลาดในจังหวัดเพื่อหมักก๊าซชีวภาพสำหรับชุมชนและโรงงานไฟฟ้า',
    indicator: 'กำลังการผลิตก๊าซชีวภาพเทียบเท่าไฟฟ้า',
    unit: 'kW',
    target_value: 1200,
    current_value: 600,
    budget_baht: 15000000,
    agency: 'สำนักงานพลังงานจังหวัดสระบุรี',
    status: 'In Progress'
  },
  {
    id: 9,
    name: 'โครงการธนาคารขยะชุมชนและโรงเรียนคาร์บอนต่ำ (Zero Waste Schools)',
    dimension_id: 3,
    dimension_name: 'Waste Management',
    description: 'สร้างพฤติกรรมการคัดแยกขยะตั้งแต่ต้นทางผ่านโรงเรียนและศูนย์เรียนรู้ชุมชน 13 อำเภอ',
    indicator: 'จำนวนชุมชนที่เข้าร่วมโครงการแยกขยะและเปิดธนาคารขยะ',
    unit: 'ชุมชน',
    target_value: 100,
    current_value: 65,
    budget_baht: 3000000,
    agency: 'ทสจ.สระบุรี',
    status: 'In Progress'
  },
  // มิติที่ 4: เกษตรคาร์บอนต่ำ
  {
    id: 10,
    name: 'โครงการทำนาเปียกสลับแห้ง (Alternate Wet and Dry: AWD)',
    dimension_id: 4,
    dimension_name: 'Low-Carbon Agriculture',
    description: 'ส่งเสริมให้เกษตรกรทำนาข้าวแบบเปียกสลับแห้งเพื่อลดก๊าซมีเทนและประหยัดน้ำ ครอบคลุมพื้นที่เป้าหมาย 50,000 ไร่',
    indicator: 'พื้นที่ทำนาเปียกสลับแห้งสะสม',
    unit: 'ไร่',
    target_value: 50000,
    current_value: 18500,
    budget_baht: 8000000,
    agency: 'เกษตรจังหวัดสระบุรี',
    status: 'In Progress'
  },
  {
    id: 11,
    name: 'โครงการส่งเสริมปลูกหญ้าเนเปียร์เป็นพืชพลังงานร่วมชุมชน',
    dimension_id: 4,
    dimension_name: 'Low-Carbon Agriculture',
    description: 'สนับสนุนเกษตรกรปลูกหญ้าโตเร็วเพื่อส่งจำหน่ายให้กับโรงไฟฟ้าชีวมวลและโรงงานปูนซีเมนต์',
    indicator: 'พื้นที่ปลูกหญ้าเนเปียร์พืชพลังงาน',
    unit: 'ไร่',
    target_value: 12000,
    current_value: 4800,
    budget_baht: 5000000,
    agency: 'เกษตรจังหวัดสระบุรี',
    status: 'In Progress'
  },
  // มิติที่ 5: เพิ่มพื้นที่สีเขียว
  {
    id: 12,
    name: 'โครงการฟื้นฟูเหมืองหินและป่าชุมชนเฉลิมพระเกียรติ',
    dimension_id: 5,
    dimension_name: 'Green Areas & Community Forests',
    description: 'ฟื้นฟูสภาพเหมืองหินปูนที่หมดอายุประทานบัตรให้กลายเป็นแหล่งท่องเที่ยวเชิงนิเวศและพื้นที่ป่าชุมชน',
    indicator: 'พื้นที่ป่าชุมชนและเหมืองหินที่ได้รับการฟื้นฟู',
    unit: 'ไร่',
    target_value: 15000,
    current_value: 6200,
    budget_baht: 18000000,
    agency: 'ทสจ.สระบุรี',
    status: 'In Progress'
  },
  {
    id: 13,
    name: 'เครือข่ายป่าชุมชนคาร์บอนเครดิตสระบุรี (45 ป่าชุมชน)',
    dimension_id: 5,
    dimension_name: 'Green Areas & Community Forests',
    description: 'ขึ้นทะเบียนป่าชุมชน 45 แห่งเข้าร่วมโครงการ T-VER ขององค์การบริหารจัดการก๊าซเรือนกระจก (TGO)',
    indicator: 'จำนวนป่าชุมชนที่ได้รับการขึ้นทะเบียนคาร์บอนเครดิต',
    unit: 'แห่ง',
    target_value: 45,
    current_value: 22,
    budget_baht: 6000000,
    agency: 'ทสจ.สระบุรี',
    status: 'In Progress'
  },
  {
    id: 14,
    name: 'ป่าไม้ในเมืองและทางเดินสีเขียว (Urban Pocket Parks)',
    dimension_id: 5,
    dimension_name: 'Green Areas & Community Forests',
    description: 'เพิ่มพื้นที่สีเขียวขนาดเล็กในเขตเทศบาลเมืองสระบุรี แก่งคอย และเฉลิมพระเกียรติ',
    indicator: 'พื้นที่สวนสาธารณะและทางเดินสีเขียวในเมือง',
    unit: 'ตารางเมตร',
    target_value: 50000,
    current_value: 20000,
    budget_baht: 12000000,
    agency: 'ท้องถิ่นจังหวัดสระบุรี',
    status: 'In Progress'
  },
  // มิติที่ 6: ขนส่งและโลจิสติกส์
  {
    id: 15,
    name: 'ส่งเสริมยานยนต์ไฟฟ้า (EV) ในกลุ่มรถบรรทุกขนส่งอุตสาหกรรม',
    dimension_id: 6,
    dimension_name: 'Transport & Logistics',
    description: 'ร่วมมือกับสมาคมขนส่งสระบุรีเปลี่ยนผ่านหัวลากปูนซีเมนต์เป็น EV Truck',
    indicator: 'สัดส่วนรถบรรทุกขนส่งปูนที่เป็น EV',
    unit: '%',
    target_value: 20,
    current_value: 3.5,
    budget_baht: 45000000,
    agency: 'ขนส่งจังหวัดสระบุรี',
    status: 'In Progress'
  },
  {
    id: 16,
    name: 'โครงข่ายสถานีอัดประจุไฟฟ้าความเร็วสูงสำหรับรถบรรทุกหนัก (Heavy-Duty EV Charging Stations)',
    dimension_id: 6,
    dimension_name: 'Transport & Logistics',
    description: 'จัดตั้งสถานีชาร์จกำลังสูง (DC Ultra Fast Charge) ตามเส้นทางขนส่งสายหลัก',
    indicator: 'จำนวนจุดบริการชาร์จสำหรับรถบรรทุกขนาดใหญ่',
    unit: 'แห่ง',
    target_value: 8,
    current_value: 2,
    budget_baht: 24000000,
    agency: 'สำนักงานพลังงานจังหวัดสระบุรี',
    status: 'In Progress'
  },
  {
    id: 17,
    name: 'ระบบบริการขนส่งสาธารณะไฟฟ้าในเมือง (EV Smart Shuttle)',
    dimension_id: 6,
    dimension_name: 'Transport & Logistics',
    description: 'นำร่องรถมินิบัสไฟฟ้าให้บริการฟรีรอบตัวเมืองสระบุรีเพื่อลดมลพิษ PM2.5 และคาร์บอน',
    indicator: 'จำนวนผู้โดยสารใช้บริการต่อวัน',
    unit: 'คน/วัน',
    target_value: 1500,
    current_value: 650,
    budget_baht: 9500000,
    agency: 'ท้องถิ่นจังหวัดสระบุรี',
    status: 'In Progress'
  }
];

export const initialSummaryData = {
  gpp_gdp_saraburi_thb: '245,000,000,000',
  cement_production_pct_national: 80,
  national_ghg_emissions_rank: 3,
  reduction_target_tons_co2e: 5000000,
  current_reduced_tons_co2e: 3250000,
  target_year: 2027,
  total_projects: 17,
  active_projects: 15,
  pilot_areas_target: 38,
  pilot_areas_current: 26,
  core_dimensions_target: 6,
  core_dimensions_current: 6,
  forest_target_rai: 15000,
  forest_current_rai: 10500,
  agri_target_rai: 50000,
  agri_current_rai: 28500,
  total_budget_baht: 367000000,
  partnership_model: '4Ps (Public-Private-People Partnership)',
  wef_initiative_member: true
};

export const initialCmsArticles = [];

export const initialActivities = [
  {
    id: 1,
    project_id: 1,
    title: 'ลงนามความร่วมมือการใช้ปูนไฮดรอลิก มอก. 2594 ในกลุ่มเทศบาลนำร่อง',
    location: 'เทศบาลเมืองสระบุรี',
    description: 'จัดอบรมการผสมคอนกรีตและการประยุกต์ใช้งานโครงสร้างพื้นฐานท้องถิ่นแก่ผู้รับเหมาก่อสร้างและช่างโยธา',
    carbon_saved_co2e: 125.40,
    budget_spent_baht: 150000,
    activity_date: '2026-06-15',
    image_url: 'https://images.unsplash.com/photo-1590069261209-f8e9b8642343?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 2,
    project_id: 4,
    title: 'เปิดตัวทดลองจ่ายไฟเฟสแรก โซลาร์ลอยน้ำคลองเพรียว',
    location: 'อ่างเก็บน้ำคลองเพรียว อ.เมือง',
    description: 'ติดตั้งแล้วเสร็จ 2.5 MW เริ่มเดินเครื่องจ่ายไฟทดลองเข้าอาคารหน่วยงานราชการและศูนย์บริการสาธารณสุข',
    carbon_saved_co2e: 340.20,
    budget_spent_baht: 45000000,
    activity_date: '2026-07-10',
    image_url: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 3,
    project_id: 10,
    title: 'จัดกิจกรรมตรวจวัดระดับก๊าซมีเทนและสาธิตการทำนาเปียกสลับแห้ง (AWD)',
    location: 'ต.หนองแซง อ.หนองแซง',
    description: 'เกษตรกรเข้าร่วมอบรมกว่า 120 ราย เพื่อเรียนรู้วิธีการติดตั้งท่อวัดน้ำและสลับการระบายน้ำเพื่อลดการหมักของก๊าซมีเทนในดิน',
    carbon_saved_co2e: 85.00,
    budget_spent_baht: 90000,
    activity_date: '2026-07-22',
    image_url: 'https://images.unsplash.com/photo-1530595467537-0b5996c41f2d?auto=format&fit=crop&w=400&q=80'
  }
];

